/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx,html}",
    "./src/components/**/*.{vue,js,ts}",
    "./src/pages/**/*.{vue,js,ts}",
    "./public/**/*.html",
  ],
  theme: {
    fontFamily: {
      'sans': ['Colmeak', 'var(--font-colmeak)', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'system-ui', 'sans-serif'],
      'serif': ['Colmeak', 'var(--font-colmeak)', 'ui-serif', 'Georgia', 'serif'],
      'mono': ['Colmeak', 'var(--font-colmeak)', 'ui-monospace', 'SFMono-Regular', 'monospace'],
    },
    extend: {
      fontFamily: {
        'colmeak': ['var(--font-colmeak)'],
        'colmeak-light': ['var(--font-colmeak-light)'],
        'colmeak-regular': ['var(--font-colmeak-regular)'],
        'colmeak-medium': ['var(--font-colmeak-medium)'],
        'colmeak-semibold': ['var(--font-colmeak-semibold)'],
        'colmeak-bold': ['var(--font-colmeak-bold)'],
        'colmeak-extrabold': ['var(--font-colmeak-extrabold)'],
        'colmeak-black': ['var(--font-colmeak-black)'],
        // Alias de compatibilité pour Codega
        'codega': ['var(--font-colmeak)'],
        'codega-light': ['var(--font-colmeak-light)'],
        'codega-regular': ['var(--font-colmeak-regular)'],
        'codega-medium': ['var(--font-colmeak-medium)'],
        'codega-semibold': ['var(--font-colmeak-semibold)'],
        'codega-bold': ['var(--font-colmeak-bold)'],
        'codega-extrabold': ['var(--font-colmeak-extrabold)'],
        'codega-black': ['var(--font-colmeak-black)'],
      },
      colors: {
        'blue-ribbon': {
          50: '#efefff',
          100: '#d7d7ff',
          200: '#8f90ff',
          300: '#6d6fff',
          400: '#373cff',
          500: '#0012ee',
          600: '#00046d',
          700: '#00024c',
        },
        'white': {
          50: '#ffffff',
          100: '#f8f8f8',
          200: '#e2e2e2',
          300: '#c7c7c7',
          400: '#a6a6a6',
          500: '#737373',
          600: '#464646',
          700: '#2d2d2d',
          800: '#1d1d1d',
          900: '#101010',
          950: '#050505',
        },
        'cerise': {
          50: '#ffecf1',
          100: '#ffcedc',
          200: '#ff9dbc',
          300: '#ff68a1',
          400: '#fd0088',
          500: '#d1006f',
          600: '#b50060',
          700: '#91004b',
          800: '#690035',
          900: '#40001e',
          950: '#2b0012',
        },
        'pink-flamingo': {
          50: '#f8edfd',
          100: '#f1d6fa',
          200: '#e5b1f6',
          300: '#dc8ef2',
          400: '#d469ee',
          500: '#ca3fe7',
          600: '#ae35c7',
          700: '#88279c',
          800: '#5f196e',
          900: '#360a3f',
          950: '#210427',
        },
      },
    },
  },
  plugins: [],
}

